name: Build & Unit Test

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit test
        run: docker-compose run --rm echo-server go test ./... -v

      - name: Build test
        run: docker build .

